// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/search-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/shopify.ts
var SHOPIFY_API_VERSION = "2025-07";
var SHOPIFY_STORE_DOMAIN = "archive-curated-space-3cl85.myshopify.com";
var SHOPIFY_STOREFRONT_URL = `https://${SHOPIFY_STORE_DOMAIN}/api/${SHOPIFY_API_VERSION}/graphql.json`;
var SHOPIFY_STOREFRONT_TOKEN = "de7a6b056442663f558d046ceaaa3469";
async function storefront(query, variables = {}) {
  const res = await fetch(SHOPIFY_STOREFRONT_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-Shopify-Storefront-Access-Token": SHOPIFY_STOREFRONT_TOKEN
    },
    body: JSON.stringify({ query, variables })
  });
  if (!res.ok) {
    throw new Error(`Shopify Storefront API error [${res.status}]: ${await res.text()}`);
  }
  const json = await res.json();
  if (json.errors) {
    throw new Error(`Shopify GraphQL errors: ${JSON.stringify(json.errors)}`);
  }
  return json.data;
}
var STOREFRONT_URL = `https://flthy.lovable.app`;

// src/lib/mcp/tools/search-products.ts
var QUERY = `
  query SearchProducts($query: String, $first: Int!) {
    products(first: $first, query: $query) {
      edges {
        node {
          id
          handle
          title
          vendor
          productType
          description
          priceRange { minVariantPrice { amount currencyCode } }
          images(first: 1) { edges { node { url altText } } }
        }
      }
    }
  }
`;
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search the FlthyMrkt storefront catalog by keyword, brand, or product type. Returns public product listings with price, image, and a link to the product page.",
  inputSchema: {
    query: z.string().trim().default("").describe(
      "Free-text search. Supports Shopify query syntax such as `vendor:Nike` or `product_type:Tops`. Empty string returns recent products."
    ),
    limit: z.number().int().min(1).max(50).default(10).describe("Maximum number of products to return (1\u201350).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, limit }) => {
    const data = await storefront(QUERY, {
      query: query || null,
      first: limit
    });
    const products = data.products.edges.map(({ node }) => ({
      id: node.id,
      handle: node.handle,
      title: node.title,
      brand: node.vendor,
      productType: node.productType,
      price: `${node.priceRange.minVariantPrice.amount} ${node.priceRange.minVariantPrice.currencyCode}`,
      image: node.images.edges[0]?.node.url ?? null,
      url: `${STOREFRONT_URL}/product/${node.handle}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(products, null, 2) }],
      structuredContent: { products }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var QUERY2 = `
  query GetProduct($handle: String!) {
    productByHandle(handle: $handle) {
      id
      handle
      title
      description
      vendor
      productType
      tags
      priceRange { minVariantPrice { amount currencyCode } }
      images(first: 10) { edges { node { url altText } } }
      variants(first: 25) {
        edges {
          node {
            id
            title
            availableForSale
            price { amount currencyCode }
            selectedOptions { name value }
          }
        }
      }
    }
  }
`;
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Fetch full public details for a single FlthyMrkt product by its Shopify handle (URL slug), including variants, images, price, and availability.",
  inputSchema: {
    handle: z2.string().trim().min(1).describe("Product handle / URL slug, e.g. `vintage-denim-jacket`.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ handle }) => {
    const data = await storefront(QUERY2, { handle });
    const p = data.productByHandle;
    if (!p) {
      return {
        content: [{ type: "text", text: `No product found for handle: ${handle}` }],
        isError: true
      };
    }
    const product = {
      id: p.id,
      handle: p.handle,
      title: p.title,
      description: p.description,
      brand: p.vendor,
      productType: p.productType,
      tags: p.tags,
      price: `${p.priceRange.minVariantPrice.amount} ${p.priceRange.minVariantPrice.currencyCode}`,
      images: p.images.edges.map((e) => ({ url: e.node.url, alt: e.node.altText })),
      variants: p.variants.edges.map((e) => ({
        id: e.node.id,
        title: e.node.title,
        available: e.node.availableForSale,
        price: `${e.node.price.amount} ${e.node.price.currencyCode}`,
        options: e.node.selectedOptions
      })),
      url: `${STOREFRONT_URL}/product/${p.handle}`
    };
    return {
      content: [{ type: "text", text: JSON.stringify(product, null, 2) }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/tools/list-brands.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
var QUERY3 = `
  query BrandVendors($first: Int!) {
    products(first: $first) {
      edges { node { vendor } }
    }
  }
`;
var list_brands_default = defineTool3({
  name: "list_brands",
  title: "List brands",
  description: "Return the distinct set of brand names (Shopify vendors) currently carried on the FlthyMrkt storefront.",
  inputSchema: {
    sample: z3.number().int().min(50).max(250).default(250).describe("How many products to scan when building the brand list.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ sample }) => {
    const data = await storefront(
      QUERY3,
      { first: sample }
    );
    const brands = Array.from(
      new Set(
        data.products.edges.map((e) => (e.node.vendor || "").trim()).filter(Boolean)
      )
    ).sort((a, b) => a.localeCompare(b));
    return {
      content: [{ type: "text", text: JSON.stringify(brands, null, 2) }],
      structuredContent: { brands }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "flthymrkt-mcp",
  title: "FlthyMrkt",
  version: "0.1.0",
  instructions: "Public tools for the FlthyMrkt storefront. Use `search_products` to find items by keyword, brand, or product type; `get_product` to fetch full details for a product handle; and `list_brands` to see the brands currently in stock.",
  tools: [search_products_default, get_product_default, list_brands_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
